spring:
  docker:
    compose:
      enabled: true
      file: spark-batch-daily-sales-report-job/compose.yml
  data:
    mongodb:
      uri: mongodb://localhost:27017

logging:
  logback:
    rollingpolicy:
      clean-history-on-start: true
  file:
    path: logs
    name: ${logging.file.path}/application.log
  level:
    ROOT: info
    #    '[org.springframework.data.mongodb.core.MongoTemplate]': debug
#    '[org.springframework.batch]': debug
debug: false

# ===================================================================
# Application specific properties
# Add your own application properties here
# ===================================================================

#------------------------- Job configurations -------------------------
ksoot:
  job:
    correlation-id: ${spring.cloud.task.external-execution-id:daily-sales-report-job-execution-1}
    persist: true

#------------------------- Spark configurations -------------------------
spark:
  master: local
  executor:
    instances: 2
    memory: 1g
    cores: 1
  driver:
    memory: 2g
    cores: 2
  ui:
    enabled: false