global:
    scrape_interval: 5s
    evaluation_interval: 5s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['host.docker.internal:9090']
    - job_name: 'tempo'
      static_configs:
        - targets: ['host.docker.internal:3200']
    - job_name: 'spark-job-service'
      metrics_path: '/actuator/prometheus'
      scrape_interval: 3s
      static_configs:
        - targets: ['192.168.1.2:8090']
